import { Button } from '@/components/ui/button';
import { ArrowLeft, AlertTriangle, FileText, CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PageMeta from '@/components/common/PageMeta';

export default function TermsOfService() {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-background text-foreground py-12 px-4 md:px-8">
            <PageMeta
                title="Terms of Service | Secret Room"
                description="Terms of usage for the Secret Room anonymous chat platform. By using our service, you agree to these guidelines."
            />

            <div className="max-w-4xl mx-auto space-y-8">
                <div className="flex items-center gap-4 mb-8">
                    <Button variant="ghost" size="icon" onClick={() => navigate('/')}>
                        <ArrowLeft className="w-6 h-6" />
                    </Button>
                    <h1 className="text-3xl md:text-4xl font-black gradient-text">Terms of Service</h1>
                </div>

                <div className="prose dark:prose-invert max-w-none space-y-12">

                    <section className="space-y-4">
                        <p className="text-lg text-muted-foreground leading-relaxed">
                            By accessing Secret Room, you agree to the following terms. Our platform is designed for free expression and privacy, but this freedom comes with responsibility.
                        </p>
                    </section>

                    <section className="space-y-6">
                        <h2 className="text-2xl font-bold flex items-center gap-2">
                            <FileText className="w-6 h-6 text-primary" />
                            1. Acceptable Use
                        </h2>
                        <div className="bg-muted/30 p-6 rounded-2xl border border-border/50">
                            <ul className="space-y-3">
                                <li className="flex gap-3">
                                    <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
                                    <span><strong>Do</strong> share secrets, confessions, and honest thoughts safely.</span>
                                </li>
                                <li className="flex gap-3">
                                    <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
                                    <span><strong>Do</strong> respect the anonymity of other participants.</span>
                                </li>
                                <li className="flex gap-3">
                                    <AlertTriangle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
                                    <span><strong>Do NOT</strong> use this platform for illegal activities, detailed threats of violence, or distributing child exploitation material.</span>
                                </li>
                            </ul>
                        </div>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold">2. Liability Disclaimer</h2>
                        <p className="text-muted-foreground">
                            Secret Room is a communication tool provided "as is". We are <strong>not responsible</strong> for the content generated by users. Because of our encryption and zero-knowledge policy, we cannot moderate private rooms in real-time. Users assume full responsibility for their interactions.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold">3. Account & Termination</h2>
                        <p className="text-muted-foreground">
                            We reserve the right to ban IPs or terminate access for any user found attempting to exploit the system, compromise the security of other users, or conduct DoS attacks against our infrastructure.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold">4. Refunds & Payments</h2>
                        <p className="text-muted-foreground">
                            Payments for "Room Extensions" or "Premium Rooms" are processed securely. Due to the ephemeral nature of the service (consumable time), refunds are generally not provided once the time has been credited to a room, unless there is a verifiable system failure.
                        </p>
                    </section>

                    <section className="space-y-4 pt-8 border-t border-border">
                        <p className="text-sm text-muted-foreground text-center">
                            Questions regarding these terms? Contact <a href="mailto:business@entrext.in" className="text-primary hover:underline">business@entrext.in</a>.
                        </p>
                    </section>

                </div>
            </div>
        </div>
    );
}
